### ISSUE TITLE
Getting Error after hitting Authorize "Could not acquire token"

### ISSUE THREAD

**Issue by ajaykeshri** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#19]
Hi Team,
Using Xcode 11.1
MacOS Cataline 10.15

I clone this  "active-directory-b2c-ios-swift-native-msal"  and try to run getting Error "Could not acquire token: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Failed to start an interactive session, MSALInternalErrorCodeKey=-42008, MSALCorrelationIDKey=C9207A45-6A7D-416B-90E4-93E08F28A637}"
After changing B2C details same issue getting .
Please let me know what  is issue, Is this issue for Xcode/OS/MSAL version ??

**Comment by Hiteksha93** [comment]
Hi Team,

Using Xcode 11.2
macOS Mojave 10.14.5

I clone this "active-directory-b2c-ios-swift-native-msal" and try to run with the same tenant information provided in that its working fine for me.

I create my own azure tenant id and application on the Azure portal and replace the required information(B2C details) as per the mentioned steps for the ios code base. 

when i try to run application with new tenant its getting Error "Could not acquire token: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Failed to start an interactive session, MSALInternalErrorCodeKey=-42008, MSALCorrelationIDKey=C9207A45-6A7D-416B-90E4-93E08F28A637}"

Note: the b2c credentials are working fine for the Xamarin Android app.

So, can you please let me know that is that any platform-specific issue?

**Comment by Jitenderios** [comment]
Hi @ajaykeshri ,
Were you able to resolve this issue. I am also facing the same issue.
If resolved, Can you help me how to fix this issue?
@jennyf19 
@oldalton 
Thanks,
Jitender

**Comment by jennyf19** [comment]
@ajaykeshri @Jitenderios @Hiteksha93 
Could this [branch](https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal/pull/26) resolve the issue? the endpoint should not be w/login.microsoftonline.com.

**Comment by Jitenderios** [comment]
Hi @jennyf19 
Thanks for your prompt reply to the issue. But now with this new branch, I am getting the same error.
Here is the log when I tapped on authorise button:-

Using XCODE 11.3 AND IOS 13.2.3
https://fabrikamb2c.b2clogin.com/tfp/fabrikamb2c.onmicrosoft.com/b2c_1_susi
%@ TID=963239 MSAL 1.0.0 iOS 13.2.3 [2020-01-20 05:57:13] Requiring default broker type due to app being built with iOS 13 SDK
%@ TID=963239 MSAL 1.0.0 iOS 13.2.3 [2020-01-20 05:57:13 - B53A7065-0DB2-4CB9-9C9C-2F38DBF9A2F9] [MSAL] -[MSALPublicClientApplication acquireTokenWithParameters:(
"https://fabrikamb2c.onmicrosoft.com/helloapi/demo.read"
)
extraScopesToConsent:(null)
account:Masked(null)
loginHint:Masked(null)
promptType:MSALPromptTypeSelectAccount
extraQueryParameters:(null)
authority:<MSALB2CAuthority: 0x282b473e0>
webviewType:MSALWebviewTypeDefault
customWebview:No
correlationId:(null)
capabilities:(null)
claimsRequest:(null)]
%@ TID=963239 MSAL 1.0.0 iOS 13.2.3 [2020-01-20 05:57:13 - B53A7065-0DB2-4CB9-9C9C-2F38DBF9A2F9] [MSAL] Beginning interactive flow.
%@ TID=963239 MSAL 1.0.0 iOS 13.2.3 [2020-01-20 05:57:13 - B53A7065-0DB2-4CB9-9C9C-2F38DBF9A2F9] [MSAL] Resolving authority: Masked(not-null), upn: Masked(null)
%@ TID=963239 MSAL 1.0.0 iOS 13.2.3 [2020-01-20 05:57:13 - B53A7065-0DB2-4CB9-9C9C-2F38DBF9A2F9] [MSAL] Resolved authority, validated: NO, error: -51114
%@ TID=963239 MSAL 1.0.0 iOS 13.2.3 [2020-01-20 05:57:13 - B53A7065-0DB2-4CB9-9C9C-2F38DBF9A2F9] [MSAL] Interactive flow finished result (null), error: -51114 error domain: MSIDErrorDomain
%@ TID=963239 MSAL 1.0.0 iOS 13.2.3 [2020-01-20 05:57:13 - B53A7065-0DB2-4CB9-9C9C-2F38DBF9A2F9] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50000) Masked(not-null)
Could not acquire token: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Authority validation is not supported for this type of authority, MSALInternalErrorCodeKey=-42008, MSALCorrelationIDKey=B53A7065-0DB2-4CB9-9C9C-2F38DBF9A2F9}

**Comment by jennyf19** [comment]
@Jitenderios are you setting the known authority?
```swift
let b2cApplicationConfig = MSALPublicClientApplicationConfig(clientId: "your-client-id", redirectUri: "your-redirect-uri", authority: b2cAuthority)
b2cApplicationConfig.knownAuthorities = [b2cAuthority]
```

**Comment by oldalton** [comment]
Please also see [this document](https://docs.microsoft.com/en-us/azure/active-directory/develop/config-authority#change-the-default-authority) for additional informations and steps needed. Thanks!

**Comment by jennyf19** [comment]
@ajaykeshri @Hiteksha93 @Jitenderios Sample has been updated.

**Comment by Jitenderios** [comment]
Hi @jennyf19 @oldalton 

Thanks for the quick reply.

I have cloned the updated sample and ran the code with the existing credentials, it worked fine. But when I replaced it with my credentials, it showed error when i tapped on authorise button. Can I share my sample project to you to verify if the credentials which i am passing are all correct?

Here is the printed log when i ran the code with my credentials. The error this time is different than what i was getting earlier.

https://ibotcontrols.b2clogin.com/ibotcontrols.onmicrosoft.com/b2c_1_0701/oauth2/v2.0/authorize?p=B2C_1_0701&client_id=46555959-acc8-4e32-bc82-39645e482495&nonce=defaultNonce&redirect_uri=msauth.com.microsoft.identity.client.sample.MSALiOSB2C://auth&scope=openid&response_type=id_token&prompt=login
%@ TID=1107432 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:30] Requiring default broker type due to app being built with iOS 13 SDK
%@ TID=1107432 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:30 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] -[MSALPublicClientApplication acquireTokenWithParameters:(
"https://ibotcontrols.onmicrosoft.com/46555959-acc8-4e32-bc82-39645e482495/demo.read"
)
extraScopesToConsent:(null)
account:Masked(null)
loginHint:Masked(null)
promptType:MSALPromptTypeSelectAccount
extraQueryParameters:(null)
authority:<MSALB2CAuthority: 0x280889ce0>
webviewType:MSALWebviewTypeDefault
customWebview:No
correlationId:(null)
capabilities:(null)
claimsRequest:(null)]
%@ TID=1107432 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:30 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] Beginning interactive flow.
%@ TID=1107432 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:30 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] Resolving authority: Masked(not-null), upn: Masked(null)
%@ TID=1107432 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:30 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] Resolved authority, validated: NO, error: 0
%@ TID=1107432 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:30 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] No cached preferred_network for authority
%@ TID=1107622 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:31 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] Http error raised. Http Code: 404 Description Masked(not-null)
%@ TID=1107622 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:31 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] Interactive flow finished result (null), error: -51500 error domain: MSIDHttpErrorCodeDomain
%@ TID=1107622 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:31 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50000) Masked(not-null)
Could not acquire token: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=not found, MSALHTTPResponseCodeKey=404, MSALCorrelationIDKey=24FC61FF-8B0A-4432-973A-8BCD78E23240, MSALInternalErrorCodeKey=-42007, MSALHTTPHeadersKey=<CFBasicHash 0x281d08540 [0x1ef2a35e0]>{type = immutable dict, count = 9,
entries =>
0 : X-Content-Type-Options = nosniff
1 : Content-Type = text/html
3 : Strict-Transport-Security = <CFString 0x281d07580 [0x1ef2a35e0]>{contents = "max-age=31536000; includeSubDomains"}
6 : Date = <CFString 0x2806fe4c0 [0x1ef2a35e0]>{contents = "Tue, 21 Jan 2020 05:56:30 GMT"}
7 : x-ms-gateway-requestid = <CFString 0x281d074c0 [0x1ef2a35e0]>{contents = "015abcb6-3d4b-4d8f-b92d-784a65325d2b"}
8 : X-Frame-Options = DENY
9 : X-XSS-Protection = <CFString 0x2808b3e80 [0x1ef2a35e0]>{contents = "1; mode=block"}
10 : Content-Length = 1245
11 : Cache-Control = private
}
}

**Comment by jennyf19** [comment]
@ajaykeshri this issue has been resolved. want to check w/the latest version of the sample?

**Comment by jennyf19** [comment]
closing as @Jitenderios confirms the updates to the sample have resolved the issue. @ajaykeshri , please reopen or create a new issue if you still have problems. thanks.

**Comment by Jins17994** [comment]
> Hi @jennyf19 @oldalton
> 
> Thanks for the quick reply.
> 
> I have cloned the updated sample and ran the code with the existing credentials, it worked fine. But when I replaced it with my credentials, it showed error when i tapped on authorise button. Can I share my sample project to you to verify if the credentials which i am passing are all correct?
> 
> Here is the printed log when i ran the code with my credentials. The error this time is different than what i was getting earlier.
> 
> https://ibotcontrols.b2clogin.com/ibotcontrols.onmicrosoft.com/b2c_1_0701/oauth2/v2.0/authorize?p=B2C_1_0701&client_id=46555959-acc8-4e32-bc82-39645e482495&nonce=defaultNonce&redirect_uri=msauth.com.microsoft.identity.client.sample.MSALiOSB2C://auth&scope=openid&response_type=id_token&prompt=login
> %@ TID=1107432 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:30] Requiring default broker type due to app being built with iOS 13 SDK
> %@ TID=1107432 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:30 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] -[MSALPublicClientApplication acquireTokenWithParameters:(
> "https://ibotcontrols.onmicrosoft.com/46555959-acc8-4e32-bc82-39645e482495/demo.read"
> )
> extraScopesToConsent:(null)
> account:Masked(null)
> loginHint:Masked(null)
> promptType:MSALPromptTypeSelectAccount
> extraQueryParameters:(null)
> authority:<MSALB2CAuthority: 0x280889ce0>
> webviewType:MSALWebviewTypeDefault
> customWebview:No
> correlationId:(null)
> capabilities:(null)
> claimsRequest:(null)]
> %@ TID=1107432 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:30 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] Beginning interactive flow.
> %@ TID=1107432 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:30 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] Resolving authority: Masked(not-null), upn: Masked(null)
> %@ TID=1107432 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:30 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] Resolved authority, validated: NO, error: 0
> %@ TID=1107432 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:30 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] No cached preferred_network for authority
> %@ TID=1107622 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:31 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] Http error raised. Http Code: 404 Description Masked(not-null)
> %@ TID=1107622 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:31 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] Interactive flow finished result (null), error: -51500 error domain: MSIDHttpErrorCodeDomain
> %@ TID=1107622 MSAL 1.0.0 iOS 13.2.3 [2020-01-21 05:56:31 - 24FC61FF-8B0A-4432-973A-8BCD78E23240] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50000) Masked(not-null)
> Could not acquire token: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=not found, MSALHTTPResponseCodeKey=404, MSALCorrelationIDKey=24FC61FF-8B0A-4432-973A-8BCD78E23240, MSALInternalErrorCodeKey=-42007, MSALHTTPHeadersKey=<CFBasicHash 0x281d08540 [0x1ef2a35e0]>{type = immutable dict, count = 9,
> entries =>
> 0 : X-Content-Type-Options = nosniff
> 1 : Content-Type = text/html
> 3 : Strict-Transport-Security = <CFString 0x281d07580 [0x1ef2a35e0]>{contents = "max-age=31536000; includeSubDomains"}
> 6 : Date = <CFString 0x2806fe4c0 [0x1ef2a35e0]>{contents = "Tue, 21 Jan 2020 05:56:30 GMT"}
> 7 : x-ms-gateway-requestid = <CFString 0x281d074c0 [0x1ef2a35e0]>{contents = "015abcb6-3d4b-4d8f-b92d-784a65325d2b"}
> 8 : X-Frame-Options = DENY
> 9 : X-XSS-Protection = <CFString 0x2808b3e80 [0x1ef2a35e0]>{contents = "1; mode=block"}
> 10 : Content-Length = 1245
> 11 : Cache-Control = private
> }
> }

I have the same issue, how do you solve it?

**Comment by jennyf19** [comment]
@Jins17994 The fix was merged in with this [PR](https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal/pull/26). It might have been a customer configuration issue, I don't remember. We'd need to see the specific error message and possibly the values [here](https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal/blob/master/MSALiOSB2C/ViewController.swift#L36).

**Comment by Jins17994** [comment]
@jennyf19  
This is the detailed error description

%@ TID=4035076 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:15] Creating Error with description: It is not B2C authority.
%@ TID=4035076 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:15] Default app's access group: "Masked(not-null)".
%@ TID=4035076 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:15] Using "Masked(not-null)" Team ID.
%@ TID=4035076 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:15] Init MSIDKeychainTokenCache with keychainGroup: Masked(not-null)
%@ TID=4035076 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:15] Creating Error with description: It is not B2C authority.
%@ TID=4035076 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:15] Requiring default broker type due to app being built with iOS 13 SDK
%@ TID=4035076 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:15 - D15F4740-C211-424C-8E43-3FAFB8BD25DA] [MSAL] -[MSALPublicClientApplication acquireTokenWithParameters:(
)
                                     extraScopesToConsent:(null)
                                                  account:Masked(null)
                                                loginHint:Masked(null)
                                               promptType:MSALPromptTypePromptIfNecessary
                                     extraQueryParameters:(null)
                                                authority:(null)
                                              webviewType:MSALWebviewTypeDefault
                                            customWebview:No
                                            correlationId:(null)
                                             capabilities:(null)
                                            claimsRequest:(null)]
%@ TID=4035076 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:15 - D15F4740-C211-424C-8E43-3FAFB8BD25DA] [MSAL] Beginning interactive flow.
%@ TID=4035076 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:15] Start background app task with type 0
%@ TID=4035076 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:15 - D15F4740-C211-424C-8E43-3FAFB8BD25DA] [MSAL] Resolving authority: Masked(not-null), upn: Masked(null)
%@ TID=4035076 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:15 - D15F4740-C211-424C-8E43-3FAFB8BD25DA] [MSAL] Resolved authority, validated: NO, error: 0
%@ TID=4035076 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:15 - D15F4740-C211-424C-8E43-3FAFB8BD25DA] [MSAL] No cached preferred_network for authority
%@ TID=4035529 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:17 - D15F4740-C211-424C-8E43-3FAFB8BD25DA] [MSAL] Http error raised. Http Code: 404 Description Masked(not-null)
%@ TID=4035529 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:17 - D15F4740-C211-424C-8E43-3FAFB8BD25DA] Creating Error with description: not found
%@ TID=4035529 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:17 - D15F4740-C211-424C-8E43-3FAFB8BD25DA] [MSAL] Interactive flow finished. Result (null), error: -51500 error domain: MSIDHttpErrorCodeDomain
%@ TID=4035529 MSAL 1.1.16 iOS Sim 14.4 [2021-04-23 16:26:17 - D15F4740-C211-424C-8E43-3FAFB8BD25DA] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50000) Masked(not-null)
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=not found, MSALHTTPResponseCodeKey=404, MSALCorrelationIDKey=D15F4740-C211-424C-8E43-3FAFB8BD25DA, MSALInternalErrorCodeKey=-42007, MSALHTTPHeadersKey=<CFBasicHash 0x60000112d8c0 [0x7fff8002eb50]>{type = immutable dict, count = 11,
entries =>
	0 : Public = <CFString 0x600000ae6b50 [0x7fff8002eb50]>{contents = "OPTIONS,TRACE,GET,HEAD,POST"}
	1 : Content-Type = text/html
	2 : Allow = <CFString 0x600000ae4210 [0x7fff8002eb50]>{contents = "OPTIONS,TRACE,GET,HEAD,POST"}
	3 : Strict-Transport-Security = <CFString 0x600001136940 [0x7fff8002eb50]>{contents = "max-age=31536000; includeSubDomains"}
	4 : X-Content-Type-Options = nosniff
	6 : Date = <CFString 0x600000ae7120 [0x7fff8002eb50]>{contents = "Fri, 23 Apr 2021 16:26:16 GMT"}
	7 : x-ms-gateway-requestid = <CFString 0x600001137840 [0x7fff8002eb50]>{contents = "d13a33ba-376c-4526-a06d-ce460498b8c2"}
	8 : X-Frame-Options = DENY
	9 : X-XSS-Protection = <CFString 0x600000401340 [0x7fff8002eb50]>{contents = "1; mode=block"}
	10 : Content-Length = 103
	11 : Cache-Control = private
}
}

**Comment by Jins17994** [comment]
@jennyf19  earlier error is : Authority validation is not supported for this type of authority. then I change _validateAuthority = NO in MSALPublicClientApplication.m file and run again then show above mentioned error.

**Comment by jennyf19** [comment]
@Jins17994 what authority are you using?

**Comment by Jins17994** [comment]
@jennyf19  Authority Url : https://markhabadev.b2clogin.com/markhabadev.onmicrosoft.com/B2C_1_dev_SignupSignin/oauth2/v2.0/authorize

this is my code : 

func msal(){
        do {
            // Create an instance of MSALPublicClientApplication with proper config
                        
            guard let authorityURL = URL(string: "https://markhabadev.b2clogin.com/markhabadev.onmicrosoft.com/B2C_1_dev_SignupSignin/oauth2/v2.0/authorize") else {
                    // Handle error
                    return
                }
            let b2cAuthority = try MSALB2CAuthority(url: authorityURL)
                // Create MSALPublicClientApplication configuration
            let b2cApplicationConfig = MSALPublicClientApplicationConfig(clientId: "***bdbb9-2622-496d-9131-d08962588***", redirectUri: "msauth.com.caspar.Markhaba://auth", authority: b2cAuthority)
            
            let b2cApplication = try MSALPublicClientApplication(configuration: b2cApplicationConfig)
            
                    
            let viewController = self /*replace with your main presentation controller here */
            let webViewParameters = MSALWebviewParameters(authPresentationViewController: viewController)
            let interactiveParameters = MSALInteractiveTokenParameters(scopes: [], webviewParameters: webViewParameters)
                    
            b2cApplication.acquireToken(with: interactiveParameters) { [self] (result, error) in
                        
                guard let result = result else {
                    print(error!) /* MSAL token acquisition failed, check error information */
                    return
                        }
                        accessToken = result.accessToken
                        let account = result.account
                        getContentWithToken()
                        currentAccount = account
                        /* MSAL token acquisition succeeded, use access token or check account */
            }
        }
        catch {
            print(error) /* MSALPublicClientApplication creation failed, check error information */
        }
        
    }
