### ISSUE TITLE
Deep Linking on Policy Page removed

### ISSUE THREAD

**Issue by kquinn1** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#5]
Our Azure B2C SignupOrSignin policy pages rendered with MSAL currently removes the href's of mobile deep links, redirect uri's in the form of appName://path, that redirect back to our mobile application. We need this functionality for our mobile application. 

We contacted Microsoft about this issue and the response was that we needed a custom domain in order to point to non absolute urls on our policy page. Our team has registered a custom domain for our tenant and are able to see mobile deep links when we view the policy in a web browser. 

However, we have not figured out the correct way to instantiate MSAL with our custom domain. You can pass in the custom domain URL as the tenant name and still obtain the token but it appears that the mobile deep links have been removed. Clicking on the links does nothing. I believe that the issue is that the url constructed in the web view starts with the domain of login.microsoft.com instead of our custom domain. How can we correctly obtain tokens and point to this domain?

**Comment by parakhj** [comment]
Could you send a snippet of the html code that includes the href? Just to be clear, you have a custom UI that includes a link that takes you back to the app. Is that correct?

If you are using Javascript, then it won't work because Azure AD B2C strips out javascript before showing the UI (for security reasons). If you are looking to add javascript into your UI, please vote for this [feature](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/15493536-add-support-for-javascript-inside-the-custom-ui-br).

Sorry for the confusion, but custom domains is not actually fully supported in Azure AD B2C at the moment, and is not available as a feature. I am assuming you acquired a domain through the Azure Active Directory menu? This will not work for Azure AD B2C

**Comment by danieldobalian** [comment]
Closing as this is out of date and the guidance has since change. Please see public docs for more on custom domains.
