### ISSUE TITLE
How to check ADB2C authenticated or not inside the application on button event?

### ISSUE THREAD

**Issue by reddy4** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#66]
I Integrated MSAL library into my iOS application, and implemented ADB2C authentication, once authentication success then navigate inside my application and perform all activities. where i work around 5mins then i stop my application. When user open application second time (after 5-10mins) on button tapping, first need to check ADB2C authentication happened or not?
Then if not authenticated need to show ADB2C login page,  incase user already authenticated need to check token is it valid token or session got expired?  
Is there any difference between **silent token**  and **refresh token**?

**Comment by juan-arias** [comment]
Hi @reddy4, you can call acquire token silent, which will let you know if the login page needs to be displayed or not.

Acquire silent token will return a token without showing a UI to the user, the library will try to get it from its local cache if needed, otherwise it will refresh it from the server.

**Comment by reddy4** [comment]
Hi @juan-arias  Thank you so much :::))
I will try same and i will let you know, hoping it will work :::))
